### ISSUE TITLE
Using custom colors in commands like tellraw displays an error

### ISSUE THREAD

**Issue by Mahlarian** [SPGoding/vscode-datapack-helper-plus#17]
1.16 has added the ability for custom colors to be used in commands like title and tellraw. However, trying to use a custom color will display an error that you're using an unsupported color. I did check in the settings to make sure I was using the MC version (which it was set to 1.16)

Extension Version: 2.1.14
VSC Version: 1.47.2
![image](https://user-images.githubusercontent.com/32558416/87874397-7e093a00-c997-11ea-8322-c992324b4c9b.png)

**Comment by Mahlarian** [comment]
Didn't see the language server repository, and realized this issue has already been reported. My bad, guess it pays to look around a little more before reporting something.

**Comment by SPGoding** [comment]
No worries 😄
