### ISSUE TITLE
Auto correct broken.

### ISSUE THREAD

**Issue by sadboi123** [SPGoding/vscode-datapack-helper-plus#51]
When I tried to put an open curly bracket, it didn't make it 2. Also, when I went to add "text":"123" (for example) it said it was wrong or something with it was incorrect.
![image](https://user-images.githubusercontent.com/82846511/115307913-e740f800-a137-11eb-9307-f15c1405f3d0.png)

**Comment by sadboi123** [comment]
here is another image
![image](https://user-images.githubusercontent.com/82846511/115308061-2707df80-a138-11eb-9cee-ae281432ea7b.png)

**Comment by SPGoding** [comment]
It looks like there's an extra quote in your second image. And I cannot reproduce the first one.

**Comment by sadboi123** [comment]
For the second image, it autocorrects to it, so I trusted it and didn't double check if anything was wrong, maybe you could fix that, too.
